name: school_timetable
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  window_manager: ^0.3.6
  flutter_smart_dialog: ^4.9.4
  font_awesome_flutter: ^10.5.0
  hive_flutter: ^1.1.0
  intl: ^0.18.1
  excel:
    git:
      url: https://github.com/BST-Forked-Projects/excel.git
  open_app_file: ^4.0.2
  flutter_riverpod: ^2.3.10
  riverpod: ^2.3.10
  file_picker:
    git:
      url: https://github.com/Emmanuelfrimpong/flutter_file_picker.git

  syncfusion_flutter_xlsio: ^22.2.11
  syncfusion_flutter_pdf: ^22.2.11

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.3
  hive_generator: ^2.0.0
  build_runner: ^2.4.5

flutter:
  uses-material-design: true
  assets:
     - assets/

# flutter packages pub run build_runner build
# flutter packages pub run build_runner build --delete-conflicting-outputs